# copy this config to ~/.config/awm/config.toml

# this is a minimal config for awm; technically you do not need any binds
# or commands but the system would not be very usable like that.
# binds other than exit must be set to be available

[binds]
exit = "Alt Escape"
window.maximize = "Alt w"
window.fullscreen = "Alt f"
window.previous = "Alt o"
window.next = "Alt p"
window.move = "Alt MouseLeft"
window.up = "Alt k"
window.down = "Alt j"
window.left = "Alt h"
window.right = "Alt l"
window.swap.up = "Alt Shift K"
window.swap.down = "Alt Shift J"
window.swap.left = "Alt Shift H"
window.swap.right = "Alt Shift L"
window.close = "Alt q"
workspace.tile = "Alt t"
workspace.open = "Alt Number"
workspace.window_to = "Alt Shift Number"

[[commands]] # Launcher
bind = "Alt space"
exec = "rofi -show drun"
