# Example awm config

# place your config at ~/.config/awm/config.toml
# or specify a config path with the -c flag

# list of commands to run on startup
startup.exec = ["hyprpaper"]

# env variables to set on startup
[[startup.env]]
WLR_RENDERER = "auto"                    # "gles2", "pixman", "vulkan"
WLR_RENDER_NO_EXPLICIT_SYNC = 0          # may need to be set to 1 on intel iGPUs (https://github.com/swaywm/sway/issues/8755)
MOZ_ENABLE_WAYLAND = 1                   # enable wayland for firefox
ELECTRON_OZONE_PLATFORM_HINT = "wayland" # set electron apps to use wayland
SDL_VIDEODRIVER = "wayland"              # set sdl apps to use wayland (e.g. osu-lazer)

[exit]
exec = ["echo \"exiting awm\""] # list of commands to run on exit

[ipc]
socket = "/tmp/awm.sock" # path to start ipc server on, sets AWM_SOCKET environment variable
enabled = true           # enable ipc server, controllable with awmsg, enabled by default
spawn = true             # enable ipc spawn command, enabled by default

[keyboard] # default keyboard layout, optional
layout = "us"
model = "pc105"
variant = ""
options = ""
repeat_rate = 25
repeat_delay = 600

# to use a cursor theme, add it to ~/.local/share/icons
# and set its directory as the theme name
[pointer.xcursor]
theme = "miku-cursor"
size = 48

[pointer.mouse]
natural_scroll = true
left_handed = false
profile = "adaptive"  # "none", "flat", "adaptive", "custom"
accel_speed = 0.0     # range from -1.0 to 1.0

[pointer.touchpad]
middle_emulation = true
natural_scroll = true
tap_to_click = true
tap_and_drag = true
drag_lock = "none"           # "none", "timeout", "enabled", "sticky"
tap_button_map = "lrm"       # "lrm", "lmr"
click_method = "buttonareas" # "none", "buttonareas", "clickfinger"
scroll_method = "2fg"        # "none", "2fg", "edge", "button"
disable_while_typing = true
profile = "adaptive"         # "none", "flat", "adaptive", "custom"
accel_speed = 0.0            # range from -1.0 to 1.0

[general]
focus_on_hover = false                                        # focus window on mouse hover, false by default
focus_on_activation = "active"                                # "none", "active", "any"
system_bell = "/usr/share/sounds/freedesktop/stereo/bell.oga" # path to system bell sound, leave empty for no sound, empty by default
minimize_to_workspace = 10                                    # move window to workspace 10 on minimize, if 0 move below all other windows in the workspace

[tiling]
method = "grid" # "none", "grid", "master", "dwindle"

[binds] # default binds which can be overwitten in your config
exit = "Alt Escape"                      # exit the window manager
window.maximize = "Alt w"                # maximize the active window
window.fullscreen = "Alt f"              # fullscreen the active window
window.previous = "Alt o"                # switch to previous window
window.next = "Alt p"                    # switch to next window
window.move = "Alt MouseLeft"            # move the active window
window.up = "Alt k"                      # move the active window up
window.down = "Alt j"                    # move the active window down
window.left = "Alt h"                    # move the active window left
window.right = "Alt l"                   # move the active window right
window.swap.up = "Alt Shift K"           # swap the active window with the window above
window.swap.down = "Alt Shift J"         # swap the active window with the window below
window.swap.left = "Alt Shift H"         # swap the active window with the window on the left
window.swap.right = "Alt Shift L"        # swap the active window with the window on the right
window.half.up = "Alt Up"                # take up the upper half of the screen
window.half.down = "Alt Down"            # take up the lower half of the screen
window.half.left = "Alt Left"            # take up the left half of the screen
window.half.right = "Alt Right"          # take up the right half of the screen
window.close = "Alt q"                   # close the active window
workspace.tile = "Alt t"                 # tile the active workspace
workspace.tile_sans = "Alt Shift T"      # tile the active workspace without the active window
workspace.open = "Alt Number"            # open workspace corresponding to the number pressed
workspace.window_to = "Alt Shift Number" # move the active window to the workspace corresponding to the number pressed
# modifiers: "Shift", "Caps", "Control", "Alt", "Mod2", "Mod3", "Logo", "Mod5",
# Number is a special token that will be replaced with the number key pressed

# name, width, height and refresh are required fields
# monitors do not need to be in the config to function
# see output names with `awmsg output list`
[[monitors]]
name = "HDMI-A-1"
enabled = true     # true by default
width = 1920
height = 1080
refresh = 60.0
x = 2560           # 0 by default
y = 720            # 0 by default
transform = "none" # "none", "90", "180", "270", "f", "f90", "f180", f270"
scale = 1.0        # 1.0 by default
adaptive = false   # adaptive sync, false by default

[[monitors]]
name = "DP-1"
width = 2560
height = 1440
refresh = 180.0

[[commands]] # Launcher
bind = "Alt space"
exec = "rofi -show drun"

[[commands]] # Screenshot
bind = "Alt c"
exec = "grim -g \"$(slurp)\" - | swappy -f -"

[[commands]] # Terminal
bind = "Alt Return"
exec = "alacritty"

# apply a rule to a window matching title and/or class
[[windowrules]]
class = "foot"      # regex match app_id / class
title = ""          # regex match title
workspace = 2       # workspace num to start on
output = "HDMI-A-1" # output name to start on
# state = "maximized" # maximized, fullscreen
geometry.x = 600
geometry.y = 400
geometry.width = 500
geometry.height = 500
