# Example awm config

# place your config at ~/.config/awm/config.toml
# or specify a config path with the -c flag

[startup]
exec = ["hyprpaper"] # list of commands to run on startup
renderer = "auto"    # "gles2", "pixman", "vulkan"

# env variables to set on startup
[[startup.env]]
MOZ_ENABLE_WAYLAND = 1                   # enable wayland for firefox
ELECTRON_OZONE_PLATFORM_HINT = "wayland" # set electron apps to use wayland

[exit]
exec = ["echo \"exiting awm\""] # list of commands to run on exit

[ipc]
enabled = true # enable ipc server, controllable with awmsg, enabled by default
spawn = true   # enable ipc spawm command, enabled by default

[keyboard] # default keyboard layout, optional
layout = "us"
model = "pc105"
variant = ""
options = ""
repeat_rate = 25
repeat_delay = 600

# to use a cursor theme, add it to ~/.local/share/icons
# and set its directory as the theme name
[pointer.xcursor]
theme = "miku-cursor"
size = 48

[pointer.mouse]
natural_scroll = true
left_handed = 0
profile = "adaptive"  # "none", "flat", "adaptive", "custom"
accel_speed = 0.0     # range from -1.0 to 1.0

[pointer.touchpad]
middle_emulation = true
natural_scroll = true
tap_to_click = true
tap_and_drag = true
drag_lock = "none"           # "none", "timeout", "enabled", "sticky"
tap_button_map = "lrm"       # "lrm", "lmr"
click_method = "buttonareas" # "none", "buttonareas", "clickfinger"
scroll_method = "2fg"        # "none", "2fg", "edge", "button"
disable_while_typing = true
profile = "adaptive"         # "none", "flat", "adaptive", "custom"
accel_speed = 0.0            # range from -1.0 to 1.0

[binds] # default binds which can be overwitten in your config
exit = "Alt Escape"
window.fullscreen = "Alt f"
window.previous = "Alt o"
window.next = "Alt p"
window.move = "Alt MouseLeft"
window.up = "Alt k"
window.down = "Alt j"
window.left = "Alt h"
window.right = "Alt l"
window.swap.up = "Alt Shift K"
window.swap.down = "Alt Shift J"
window.swap.left = "Alt Shift H"
window.swap.right = "Alt Shift L"
window.close = "Alt q"
workspace.tile = "Alt t"
workspace.open = "Alt Number"
workspace.window_to = "Alt Shift Number"
# modifiers: "Shift", "Caps", "Control", "Alt", "Mod2", "Mod3", "Logo", "Mod5",
# Number is a special token that will be replaced with the number key pressed

# name, width, height and refresh are required fields
# monitors do not need to be in the config to function
[[monitors]]
name = "HDMI-A-1"
enabled = true     # true by default
width = 1920
height = 1080
refresh = 60.0
x = 2560           # 0 by default
y = 720            # 0 by default
transform = "none" # "none", "90", "180", "270", "f", "f90", "f180", f270"
scale = 1.0        # 1.0 by default
adaptive = false   # adaptive sync, false by default

[[monitors]]
name = "DP-1"
width = 2560
height = 1440
refresh = 180.0

[[commands]] # Launcher
bind = "Alt space"
exec = "rofi -show drun"

[[commands]] # Screenshot
bind = "Alt c"
exec = "grim -g \"$(slurp)\" - | swappy -f -"

[[commands]] # Terminal
bind = "Alt Return"
exec = "alacritty"
